# Generated by Django 4.0.6 on 2022-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_confirm_password_user_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmers_name', models.CharField(max_length=255)),
                ('total_amt_paid', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dealer_name', models.CharField(max_length=100)),
                ('weight_type', models.CharField(max_length=100)),
                ('gross_weight', models.CharField(max_length=100)),
                ('gunny_bag_weight', models.CharField(max_length=100)),
                ('net_weight', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
